apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  storageClassName: ""
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  storageClassName: ""
  volumeName: mongo-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G