apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pd-name
    fsType: ext4


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  

